# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coopbrainback?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
mybatis:
  type-aliases-package: cn.cocoding.entity
  mapper-locations: classpath*:/mapper/**Mapper.xml

