# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.31.72.122:3306/coopbrainback?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456

  servlet:
    multipart:
      max-file-size: 20MB  # 单个文件的大小
      max-request-size: 200MB  # 上传文件的总大小



mybatis:
  type-aliases-package: cn.cocoding.entity
  mapper-locations: classpath*:/mapper/**Mapper.xml




fdfs:
#  connectTimeout: 600
  so-timeout: 30501 # 超时时间
  connect-timeout: 30601 # 连接超时时间

  thumb-image: # 缩略图
    width: 60
    height: 60
  trackerList:
    - 172.31.72.122:22122




Configuration:
  status: warn
  Properties: # 定义全局变量
    Property: # 缺省配置（用于开发环境）。其他环境需要在VM参数中指定，如下：
      - name: log.level.console
        value: debug
      - name: log.path
        value: /opt/logs
      - name: project.name
        value: test
  Appenders:
    Console:  # 输出到控制台
      name: CONSOLE
      target: SYSTEM_OUT
      ThresholdFilter:
        level: ${sys:log.level.console} # “sys:”表示：如果VM参数中没指定这个变量值，则使用本文件中定义的缺省全局变量值
        onMatch: ACCEPT
        onMismatch: DENY
      PatternLayout:
        pattern: "%d{yyyy-MM-dd HH:mm:ss}:%5p %10t [%15F:%3L] - %m%n"
    RollingFile: # 输出到文件，按照日期输出
      - name: ROLLING_FILE
        ignoreExceptions: false
        fileName: "${log.path}/${project.name}.log"
        filePattern: "${log.path}/${project.name}-%d{yyyy-MM-dd}.log"
        append: true
        PatternLayout:
          pattern: "%d{yyyy-MM-dd HH:mm:ss,SSS}:%5p %20t [%50F:%3L] - %m%n"
        Policies:
          TimeBasedTriggeringPolicy:
            modulate: true
            interval: 1
        DefaultRolloverStrategy:
          max: 100
  Loggers:
    Root:
      level: debug
      AppenderRef:
        - ref: CONSOLE
        - ref: ROLLING_FILE

